
TRUNCATE table ACTIVITIES ;
TRUNCATE table analysts ;
TRUNCATE table anb_investigations ;
TRUNCATE table areas ;
TRUNCATE table audits ;
TRUNCATE table backup_files;
TRUNCATE table colaboration_files;
TRUNCATE table colaboration_people;
TRUNCATE table colaboration_phones;
TRUNCATE table colaboration_vehicles;
TRUNCATE table colaboration_weapons;
TRUNCATE table colaborations;
TRUNCATE table crimes;
TRUNCATE table event_people;
TRUNCATE table event_phones;
TRUNCATE table event_vehicles;
TRUNCATE table event_weapons;
TRUNCATE table events;
TRUNCATE table helpdesk_actions;
TRUNCATE table helpdesk_screenshots;
TRUNCATE table helpdesk;
TRUNCATE table historical_archives;
TRUNCATE table investigations;
TRUNCATE table justice_net_files;
TRUNCATE table justice_nets;
TRUNCATE table justice_net_people;
TRUNCATE table localities;
TRUNCATE table office_files;
TRUNCATE table office_people;
TRUNCATE table office_phones;
TRUNCATE table office_weapons;
TRUNCATE table offices;
TRUNCATE table offices_attachments;
TRUNCATE table pdf_investigations;
TRUNCATE table people;
TRUNCATE table person_phones;
TRUNCATE table phones;
TRUNCATE table places;
TRUNCATE table priorities;
TRUNCATE table roles;
TRUNCATE table schema_migrations;
TRUNCATE table statuses;
TRUNCATE table townships;
TRUNCATE table users;
TRUNCATE table vehicles;
TRUNCATE table weapons;
TRUNCATE table weapon_types ;